[phases.setup]
nixPkgs = ["python312", "nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm --prefix frontend install"
]

[phases.build]
cmds = ["npm --prefix frontend run build"]

[start]
cmd = "uvicorn --app-dir backend main:app --host 0.0.0.0 --port $PORT"
